---
abstract: 'Domain parser and puny encoder/decoder.'
author:
  - 'Trav Holton <heytrav@cpan.org>'
build_requires:
  Net::IDN::Encode: '2.003'
  Perl::Critic: '0'
  Regexp::Assemble::Compressed: '0'
  Smart::Comments: '0'
  Test::Class: '0'
  Test::Deep: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Routine: '0'
  Unicode::CharName: '1.07'
  namespace::autoclean: '0'
configure_requires:
  Module::Build: '0.4'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ParseUtil-Domain
provides:
  ParseUtil::Domain:
    file: lib/ParseUtil/Domain.pm
    version: '2.35'
requires:
  Carp: '1.17'
  List::MoreUtils: '0'
  Net::IDN::Encode: '2.003'
  Net::IDN::Nameprep: '1.101'
  Net::IDN::Punycode: '1.1'
  Perl6::Export::Attrs: '0'
  autobox: '0'
  autobox::Core: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/heytrav/ParseUtil-Domain.git
version: '2.35'
